# -*- coding: utf-8 -*-
"""Polinomios de Interpolación de Lagrange.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1je6mtpYuTDuMgBavMqq12R-70VOwtY6N
"""

import numpy as np
import matplotlib . pyplot as plt
from scipy import interpolate
import sympy as sym

x = np . array ([0 ,1 ,2 ,3 ,4])
y = np . array ([1, 0.9 ,-1 ,-2.3 ,1.8])
n = x . size
xi =0
yi =0
10 # Calcula los factores de Lagrange y hace la suma
for i in range (0 , n ) :
    producto = y [ i ]
    for j in range (0 , n ) :
        if i != j :
            producto = producto * ( xi - x [ j ]) /( x [ i ] - x [ j ]) ;
            yi = yi + producto

print ( yi )
f = interpolate . lagrange (x , y ) # usando la funcion de Lagrange de ←-scipy
print ( f ( xi ) )

plt . plot (x ,y ,'o')
plt . plot ( xi , yi ,'sr ')
plt . text ( xi +0.1 , yi , ' Profundidad ' + str( yi ) )
plt . title ('Polinomios de Interpolación de Lagrange ')
plt . legend ([ 'Datos ',' Interpolacion '])
plt . grid ( True )