# -*- coding: utf-8 -*-
"""regresiónLineal.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vBBMZ0r1CiGqFW2-JJMBsIrv_DuJEaDu
"""

import numpy as np

# Datos
x1 = np.array([1, 1, 2, 3, 1, 2, 3, 3])
x2 = np.array([0, 1, 1, 2, 2, 3, 3, 1])
y = np.array([3.2, 6, 2.2, 2.5, 6.5, 6.6, 3.5, 0.2])

# Modelo lineal: y = b0 + b1*x1 + b2*x2
X = np.column_stack((np.ones(len(x1)), x1, x2))
beta = np.linalg.lstsq(X, y, rcond=None)[0]

# Coeficiente de correlación
y_pred = beta[0] + beta[1]*x1 + beta[2]*x2
cov = np.cov(x1, y, ddof=1)[0,1]
s_x = np.std(x1, ddof=1)
s_y = np.std(y, ddof=1)
r = cov / (s_x * s_y)

# Resultados
print(f"Pendiente: {beta[1]:.4f}")
print(f"Intersección: {beta[0]:.4f}")
print(f"Coeficiente de correlación: {r:.4f}")